framework:
    messenger:
        transports:
            async_tasks:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Account\Domain\Event\UserRegistered': async_tasks
