twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/src/Account/UserInterface/Presenter/templates'
    paths:
        '%kernel.project_dir%/src/SharedKernel/UserInterface/Presenter/templates': SharedKernel
        '%kernel.project_dir%/src/Account/UserInterface/Presenter/templates': Account
        '%kernel.project_dir%/src/Catalog/UserInterface/Presenter/templates': Catalog

when@test:
    twig:
        strict_variables: true
