version: '3.8'

services:
  ddd-php:
    build: docker/php
    container_name: ddd-php
    volumes:
      - .:/var/www/symfony:delegated
    working_dir: /var/www/symfony
    networks:
      - symfony

  ddd-nginx:
    build: docker/nginx
    container_name: ddd-nginx
    ports:
      - "8182:80"
    volumes:
      - ./docker/nginx/sites-enabled/site.conf:/etc/nginx/sites-enabled/site.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/symfony:delegated
    depends_on:
      - ddd-php
    networks:
      - symfony

  ddd-database:
    container_name: ddd-db
    build: docker/mysql
    ports:
      - 3308:3306
    volumes:
      - ./docker/mysql/scripts:/scripts # accès aux scripts custom (pour anonymisation)
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    networks:
      - symfony
    command: [
      "--wait_timeout=28800",
    ]
  ddd-rabbitmq:
    container_name: ddd-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'  # Pour l'interface de gestion
    environment:
      RABBITMQ_DEFAULT_USER: rami
      RABBITMQ_DEFAULT_PASS: rami
    networks:
      - symfony
  ddd-mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "18080:1080"  # Interface Web de MailCatcher
      - "18025:1025"  # Serveur SMTP
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
