version: '3.8'

services:
  php:
    build: docker/php
    container_name: php
    volumes:
      - .:/var/www/symfony:delegated
    working_dir: /var/www/symfony
    networks:
      - symfony

  nginx:
    build: docker/nginx
    container_name: nginx
    ports:
      - "8182:80"
    volumes:
      - ./docker/nginx/sites-enabled/site.conf:/etc/nginx/sites-enabled/site.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/symfony:delegated
    depends_on:
      - php
    networks:
      - symfony

  database:
    build: docker/mysql
    ports:
      - 3308:3306
    volumes:
      - ./docker/mysql/scripts:/scripts # accès aux scripts custom (pour anonymisation)
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    networks:
      - symfony
    command: [
      "--wait_timeout=28800",
    ]

networks:
  symfony:
    driver: bridge
