services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Account\:
    resource: '../../../src/Account/*'
    exclude:
      - '../../../src/Account/Domain/{Aggregate,Event}'
      - '../../../src/Account/Application/{Event, EventHandler}'
      - '../../../src/Account/Infrastructure/{Doctrine}'


  App\Account\UserInterface\Controller\:
    resource: '../src/Account/UserInterface/Controller/'
    tags: [ 'controller.service_arguments' ]


