services:
  _defaults:
    autowire: true
    autoconfigure: true


  App\SharedKernel\UserInterface\Controller\:
    resource: '../src/SharedKernel/UserInterface/Controller/'
    tags: [ 'controller.service_arguments' ]
