controllers_sharedKernel:
    resource:
        path: ../src/SharedKernel/UserInterface/Controller/
        namespace: App\SharedKernel\UserInterface\Controller
    type: attribute
controllers_account:
    resource:
        path: ../src/Account/UserInterface/Controller/
        namespace: App\Account\UserInterface\Controller
    type: attribute
controllers_catalog:
    resource:
        path: ../src/Catalog/UserInterface/Controller/
        namespace: App\Catalog\UserInterface\Controller
    type: attribute

app_logout:
    path: /logout
    methods: GET